const PREC = {
  token: 1,
  unknown: -1,
};

module.exports = grammar({
  name: "leo",

  extras: _ => [],

  word: $ => $.identifier,

  rules: {
    source_file: $ => repeat($._token),

    _token: $ => choice(
      $._whitespace,
      $.comment,
      $.annotation,
      $.keyword,
      $.visibility,
      $.builtin_type,
      $.boolean,
      $.none,
      $.special_expression,
      $.numeric_literal,
      $.address_literal,
      $.locator,
      $.program_id,
      $.identifier,
      $.string,
      $.operator,
      ";",
      ":",
      ",",
      ".",
      "::",
      "(",
      ")",
      "[",
      "]",
      "{",
      "}",
      $.unknown,
    ),

    _whitespace: _ => token(/[\s\uFEFF\u2060\u200B]+/),

    comment: _ => token(choice(
      seq("//", /[^\n]*/),
      seq("/*", /[^*]*\*+([^/*][^*]*\*+)*/, "/"),
    )),

    annotation: _ => token(prec(PREC.token, /@[A-Za-z_][A-Za-z0-9_]*/)),

    keyword: _ => token(prec(PREC.token, choice(
      "aleo",
      "as",
      "async",
      "assert",
      "assert_eq",
      "assert_neq",
      "const",
      "constructor",
      "else",
      "final",
      "fn",
      "for",
      "function",
      "if",
      "import",
      "in",
      "inline",
      "interface",
      "let",
      "mapping",
      "program",
      "record",
      "return",
      "script",
      "storage",
      "struct",
      "transition",
    ))),

    visibility: _ => token(prec(PREC.token, choice(
      "constant",
      "private",
      "public",
    ))),

    builtin_type: _ => token(prec(PREC.token, choice(
      "address",
      "bool",
      "boolean",
      "field",
      "Fn",
      "Final",
      "Future",
      "group",
      "i8",
      "i16",
      "i32",
      "i64",
      "i128",
      "scalar",
      "signature",
      "string",
      "u8",
      "u16",
      "u32",
      "u64",
      "u128",
    ))),

    boolean: _ => token(prec(PREC.token, choice("true", "false"))),

    none: _ => token(prec(PREC.token, "none")),

    special_expression: _ => token(prec(PREC.token, choice(
      "self",
      "self.address",
      "self.caller",
      "self.signer",
      "block",
      "block.height",
      "network",
      "network.id",
    ))),

    numeric_literal: _ => token(prec(PREC.token, choice(
      /0b[01][01_]*(u8|u16|u32|u64|u128|i8|i16|i32|i64|i128)?/,
      /0o[0-7][0-7_]*(u8|u16|u32|u64|u128|i8|i16|i32|i64|i128)?/,
      /0x[0-9A-Fa-f][0-9A-Fa-f_]*(u8|u16|u32|u64|u128|i8|i16|i32|i64|i128)?/,
      /[0-9][0-9_]*(u8|u16|u32|u64|u128|i8|i16|i32|i64|i128|field|group|scalar)?/,
    ))),

    address_literal: _ => token(prec(PREC.token, /aleo1[a-z0-9]+/)),

    locator: _ => token(prec(PREC.token, /[A-Za-z_][A-Za-z0-9_]*\.aleo\/[A-Za-z_][A-Za-z0-9_]*/)),

    program_id: _ => token(prec(PREC.token, /[A-Za-z_][A-Za-z0-9_]*\.aleo/)),

    identifier: _ => token(prec(PREC.token, /[A-Za-z_][A-Za-z0-9_]*/)),

    string: _ => token(seq(
      "\"",
      repeat(choice(
        /[^"\\\n]/,
        /\\./,
      )),
      "\"",
    )),

    operator: _ => token(prec(PREC.token, choice(
      "=>",
      "->",
      "..=",
      "..",
      "==",
      "!=",
      "<=",
      ">=",
      "&&",
      "||",
      "<<",
      ">>",
      "**",
      "+=",
      "-=",
      "*=",
      "/=",
      "%=",
      "**=",
      "<<=",
      ">>=",
      "&=",
      "|=",
      "^=",
      "&&=",
      "||=",
      "=",
      "<",
      ">",
      "!",
      "&",
      "|",
      "^",
      "+",
      "-",
      "*",
      "/",
      "%",
      "?",
    ))),

    unknown: _ => token(prec(PREC.unknown, /./)),
  },
});
